<script type="text/javascript">
        hs.graphicsDir = '<?php echo $this->getSkinUrl('css/graphics/'); ?>';
        hs.align = 'center';
        hs.transitions = ['expand', 'crossfade'];
        hs.wrapperClassName = 'dark';
        hs.fadeInOut = true;
        hs.dimmingOpacity = 0;
        hs.allowMultipleInstances = false;
        hs.dimmingOpacity = 0.5;
        hs.showCredits = false;        
        hs.cacheAjax = false;

        // Add the controlbar
        if (hs.addSlideshow) hs.addSlideshow({
                //slideshowGroup: 'group1',
                interval: 5000,
                repeat: false,
                useControls: true,
                fixedControls: 'fit',
                overlayOptions: {
                        opacity: .6,
                        position: 'bottom center',
                        hideOnMouseOut: true
                }
        });
</script>

<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
?>

<?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>

<div class="highslide-gallery product-image">
    <a href="<?php echo $this->helper('catalog/image')->init($_product, 'image') ?>" class="highslide" onclick="return hs.expand(this)">
        <img src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(650) ?>" alt="<?php echo $this->htmlEscape($this->getImageLabel()) ?>"
            title="Click to enlarge" />
    </a>
</div>

<script type="text/javascript">
//<![CDATA[
    // Event.observe(window, 'load', function() {
    //    product_zoom = new Product.Zoom('image', 'track', 'handle', 'zoom_in', 'zoom_out', 'track_hint');
    // });
//]]>
</script>

<?php endif; ?>

<?php if (count($this->getGalleryImages()) > 1): ?>
<div class="more-views">
    <div class="highslide-gallery">
    <ul>
    <?php foreach ($this->getGalleryImages() as $_image): ?>
        <li>
        <div class="highslide-caption">
            <?php echo $this->htmlEscape($_image->getLabel()) ?>
        </div>
            <a href="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile()); ?>" class="highslide" onclick="return hs.expand(this)">
               <img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(350,280); ?>" alt="<?php echo $this->htmlEscape($_image->getLabel()); ?>" />
	    </a>
       </li>
    <?php endforeach; ?>
    </ul>
    </div>
</div>
<?php endif; ?>
